name: Priority List
on:
  # schedule: [{ cron: '0 2 * * 1' }]  # 02:00 (AM, UTC) Mondays
  push: { branches: [v*] }
  pull_request:
  # configurable `workflow_dispatch.inputs` to make it easy to experiment
  workflow_dispatch:
    inputs:
      repos:
        required: true
        type: string
        default: >-
          iterative/cml
          iterative/cml.dev
          iterative/terraform-provider-iterative
          iterative/leo-server
          iterative/telemetry-python
          iterative/shtab
          iterative/features
          iterative/awesome-iterative-projects
          iterative/setup-cml
          iterative/setup-dvc
          iterative/status.cml.dev
          iterative/priority-list
          iterative/cml-playground
          iterative/cml-examples-dev
          iterative/example_cml
          iterative/cml_base_case
          iterative/cml_cloud_case
          iterative/cml_dvc_case
          iterative/cml_tensorboard_case
          iterative/cml-runner-base-case
          iterative/blog-tpi-jupyter
          iterative/blog-tpi-bees
          iterative/cml-textual-inversion
          iterative/discord-corpus
          iterative/tpi
      weight_activity:
        required: true
        type: number
        default: 14
        description: weight for number of comments
      weight_reactions:
        required: true
        type: number
        default: 7
        description: weight for reactions to original issue
      weight_staleness:
        required: true
        type: number
        default: 1
        description: weight for days of inactivity
      weight_age:
        required: true
        type: number
        default: 0.142857  # 1/7
        description: weight for days open
      multiplier_pr:
        required: true
        type: number
        default: 7
        description: weight multiplier for PRs (compared to issues)
      multiplier_labels:
        required: true
        type: string
        default: >-
          example:-1
          epic:0.142857
          blocked:0.142857
          invalid:0.142857
        description: weight multiplier for labels (negative to exclude)
      p_label_graveyard:
        required: true
        type: number
        default: 4
        description: largest pN-label (lowest priority)
jobs:
  priority-list:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with: { python-version: '3.x' }
    - if: github.event_name != 'schedule'
      uses: pre-commit/action@v3.0.0  # only for basic testing/debugging
    - name: Fetch GitHub user -> Slack member ID mapping
      run: wget https://status.cml.dev/people.json
    # - uses: iterative/priority-list@v1
    - name: Set custom defaults (for github.event_name == 'schedule')
      id: default
      run: |
        REPOS=(${{ inputs.repos }})
        if test ${#REPOS[@]} -le 0; then
          REPOS=( $(yq -r '.on.workflow_dispatch.inputs.repos.default' .github/workflows/weekly.yml) )
        fi
        echo "repos=${REPOS[@]}" >> $GITHUB_OUTPUT

        MULTIPLIER_LABELS=(${{ inputs.multiplier_labels }})
        if test ${#MULTIPLIER_LABELS[@]} -le 0; then
          REPOS=( $(yq -r '.on.workflow_dispatch.inputs.multiplier_labels.default' .github/workflows/weekly.yml) )
        fi
        echo "multiplier_labels=${MULTIPLIER_LABELS[@]}" >> $GITHUB_OUTPUT
    - uses: ./
      with:
        repos: ${{ steps.default.outputs.repos }}
        github-token: ${{ secrets.GH_TOKEN }}
        weight_activity: ${{ inputs.weight_activity }}
        weight_reactions: ${{ inputs.weight_reactions }}
        weight_staleness: ${{ inputs.weight_staleness }}
        weight_age: ${{ inputs.weight_age }}
        multiplier_pr: ${{ inputs.multiplier_pr }}
        multiplier_labels: ${{ steps.default.outputs.multiplier_labels }}
        p_label_graveyard: ${{ inputs.p_label_graveyard }}
        # slack_webhook: ${{ github.event_name == 'schedule' && secrets.SLACK_WEBHOOK || '' }}
